version: '3.8'

services:
  # Main gofred website service (nginx serving static files)
  gofred-website:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: gofred-website
    ports:
      - "3000:80"  # Map host port 3000 to container port 80 (nginx)
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    labels:
      - "com.docker.compose.project=gofred-website"
      - "description=gofred website - Build responsive web applications using only Go"
    # Resource limits (adjust based on your needs)
    deploy:
      resources:
        limits:
          memory: 128M  # Reduced since we're only serving static files
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

  # Optional: Production setup with custom nginx config and SSL
  gofred-website-ssl:
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime
    container_name: gofred-website-ssl
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro  # Mount SSL certificates if you have them
      - ./nginx-ssl.conf:/etc/nginx/nginx.conf:ro  # Use SSL-enabled config
    restart: unless-stopped
    profiles:
      - "production"  # Only start with --profile production
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      start_period: 5s
      retries: 3
    labels:
      - "com.docker.compose.project=gofred-website"
      - "description=gofred website with SSL support"
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

networks:
  default:
    name: gofred-website-network
    driver: bridge
