package home

import (
	"github.com/gofred-io/gofred/breakpoint"
	"github.com/gofred-io/gofred/foundation/button"
	"github.com/gofred-io/gofred/foundation/column"
	"github.com/gofred-io/gofred/foundation/container"
	"github.com/gofred-io/gofred/foundation/grid"
	"github.com/gofred-io/gofred/foundation/icon"
	icondata "github.com/gofred-io/gofred/foundation/icon/icon_data"
	"github.com/gofred-io/gofred/foundation/link"
	"github.com/gofred-io/gofred/foundation/row"
	"github.com/gofred-io/gofred/foundation/spacer"
	"github.com/gofred-io/gofred/foundation/text"
	"github.com/gofred-io/gofred/options"
	"github.com/gofred-io/gofred/widget"
)

func hero() widget.BaseWidget {
	return container.New(
		column.New(
			[]widget.BaseWidget{
				heroTitle(),
				heroSubtitle(),
				spacer.New(spacer.Height(8)),
				sampleCode(),
				spacer.New(spacer.Height(8)),
				cta(),
			},
			column.Gap(16),
			column.Flex(1),
			column.CrossAxisAlignment(options.AxisAlignmentTypeCenter),
			column.MainAxisAlignment(options.AxisAlignmentTypeCenter),
		),
		container.BackgroundColor("#2B799B"),
		container.Flex(1),
		container.Padding(breakpoint.All(32)),
	)
}

func heroTitle() widget.BaseWidget {
	return text.New(
		"Build responsive web apps in Go – no JavaScript required",
		text.FontSize(24),
		text.FontColor("#FFFFFF"),
		text.FontWeight("600"),
		text.UserSelect(options.UserSelectTypeNone),
	)
}

func heroSubtitle() widget.BaseWidget {
	return text.New(
		"Write modern, reactive web applications with WebAssembly using only Go.",
		text.FontSize(18),
		text.FontColor("#FFFFFF"),
		text.FontWeight("400"),
		text.UserSelect(options.UserSelectTypeNone),
	)
}

func sampleCode() widget.BaseWidget {
	closeButton := container.New(
		widget.Nil,
		container.BackgroundColor("#FF5F58"),
		container.Height(breakpoint.All(16)),
		container.Width(breakpoint.All(16)),
		container.BorderRadius(8),
	)

	fullScreenButton := container.New(
		widget.Nil,
		container.BackgroundColor("#FFBD2E"),
		container.Height(breakpoint.All(16)),
		container.Width(breakpoint.All(16)),
		container.BorderRadius(8),
	)

	minimizeButton := container.New(
		widget.Nil,
		container.BackgroundColor("#28C941"),
		container.Height(breakpoint.All(16)),
		container.Width(breakpoint.All(16)),
		container.BorderRadius(8),
	)

	windowTitle := text.New(
		"main.go",
		text.FontSize(16),
		text.FontColor("#FFFFFF"),
		text.FontWeight("500"),
		text.UserSelect(options.UserSelectTypeNone),
	)

	titleBar := row.New(
		[]widget.BaseWidget{
			row.New(
				[]widget.BaseWidget{
					closeButton,
					fullScreenButton,
					minimizeButton,
				},
				row.MainAxisAlignment(options.AxisAlignmentTypeStart),
				row.CrossAxisAlignment(options.AxisAlignmentTypeStart),
				row.Gap(8),
			),
			windowTitle,
			spacer.New(),
		},
		row.MainAxisAlignment(options.AxisAlignmentTypeStart),
		row.CrossAxisAlignment(options.AxisAlignmentTypeStart),
		row.Gap(8),
	)

	packageName := row.New(
		[]widget.BaseWidget{
			text.New(
				"package",
				text.FontSize(14),
				text.FontColor("#4F8CBF"),
				text.FontWeight("400"),
				text.UserSelect(options.UserSelectTypeNone),
			),
			text.New(
				"main",
				text.FontSize(14),
				text.FontColor("#49B8A2"),
				text.FontWeight("400"),
				text.UserSelect(options.UserSelectTypeNone),
			),
		},
		row.MainAxisAlignment(options.AxisAlignmentTypeStart),
		row.CrossAxisAlignment(options.AxisAlignmentTypeStart),
		row.Gap(6),
	)

	imports := column.New(
		[]widget.BaseWidget{
			row.New(
				[]widget.BaseWidget{
					text.New(
						"import",
						text.FontSize(14),
						text.FontColor("#AD77A8"),
						text.FontWeight("400"),
						text.UserSelect(options.UserSelectTypeNone),
					),
					text.New(
						"(",
						text.FontSize(14),
						text.FontColor("#E0BD04"),
						text.FontWeight("400"),
						text.UserSelect(options.UserSelectTypeNone),
					),
				},
				row.MainAxisAlignment(options.AxisAlignmentTypeStart),
				row.CrossAxisAlignment(options.AxisAlignmentTypeStart),
				row.Gap(6),
			),
			row.New(
				[]widget.BaseWidget{
					spacer.New(spacer.Width(6)),
					text.New(
						"\"github.com/gofred-io/gofred-website/app\"",
						text.FontSize(14),
						text.FontColor("#B9836D"),
						text.FontWeight("400"),
						text.UserSelect(options.UserSelectTypeNone),
					),
				},
				row.MainAxisAlignment(options.AxisAlignmentTypeStart),
				row.CrossAxisAlignment(options.AxisAlignmentTypeStart),
				row.Gap(6),
			),
			row.New(
				[]widget.BaseWidget{
					spacer.New(spacer.Width(6)),
					text.New(
						"\"github.com/gofred-io/gofred/application\"",
						text.FontSize(14),
						text.FontColor("#B9836D"),
						text.FontWeight("400"),
						text.UserSelect(options.UserSelectTypeNone),
					),
				},
				row.MainAxisAlignment(options.AxisAlignmentTypeStart),
				row.CrossAxisAlignment(options.AxisAlignmentTypeStart),
				row.Gap(6),
			),
			row.New(
				[]widget.BaseWidget{
					text.New(
						")",
						text.FontSize(14),
						text.FontColor("#E0BD04"),
						text.FontWeight("400"),
						text.UserSelect(options.UserSelectTypeNone),
					),
				},
			),
		},
		column.MainAxisAlignment(options.AxisAlignmentTypeStart),
		column.CrossAxisAlignment(options.AxisAlignmentTypeStart),
		column.Gap(6),
	)

	mainFunc := column.New(
		[]widget.BaseWidget{
			row.New(
				[]widget.BaseWidget{
					text.New(
						"func",
						text.FontSize(14),
						text.FontColor("#4F8CBF"),
						text.FontWeight("400"),
						text.UserSelect(options.UserSelectTypeNone),
					),
					row.New(
						[]widget.BaseWidget{
							text.New(
								"main",
								text.FontSize(14),
								text.FontColor("#DCDCAA"),
								text.FontWeight("400"),
								text.UserSelect(options.UserSelectTypeNone),
							),
							text.New(
								"()",
								text.FontSize(14),
								text.FontColor("#E0BD04"),
								text.FontWeight("400"),
								text.UserSelect(options.UserSelectTypeNone),
							),
						},
						row.MainAxisAlignment(options.AxisAlignmentTypeStart),
						row.CrossAxisAlignment(options.AxisAlignmentTypeStart),
					),
					text.New(
						"{",
						text.FontSize(14),
						text.FontColor("#E0BD04"),
						text.FontWeight("400"),
						text.UserSelect(options.UserSelectTypeNone),
					),
				},
				row.MainAxisAlignment(options.AxisAlignmentTypeStart),
				row.CrossAxisAlignment(options.AxisAlignmentTypeStart),
				row.Gap(6),
			),
			row.New(
				[]widget.BaseWidget{
					spacer.New(spacer.Width(6)),
					row.New(
						[]widget.BaseWidget{
							text.New(
								"application",
								text.FontSize(14),
								text.FontColor("#8AD1DE"),
								text.FontWeight("400"),
								text.UserSelect(options.UserSelectTypeNone),
							),
							text.New(
								".",
								text.FontSize(14),
								text.FontColor("#BCBCBC"),
								text.FontWeight("400"),
								text.UserSelect(options.UserSelectTypeNone),
							),
							text.New(
								"Run",
								text.FontSize(14),
								text.FontColor("#DCDCAA"),
								text.FontWeight("400"),
								text.UserSelect(options.UserSelectTypeNone),
							),
							text.New(
								"(",
								text.FontSize(14),
								text.FontColor("#AD77A8"),
								text.FontWeight("400"),
								text.UserSelect(options.UserSelectTypeNone),
							),
							text.New(
								"app",
								text.FontSize(14),
								text.FontColor("#8AD1DE"),
								text.FontWeight("400"),
								text.UserSelect(options.UserSelectTypeNone),
							),
							text.New(
								".",
								text.FontSize(14),
								text.FontColor("#BCBCBC"),
								text.FontWeight("400"),
								text.UserSelect(options.UserSelectTypeNone),
							),
							text.New(
								"New",
								text.FontSize(14),
								text.FontColor("#DCDCAA"),
								text.FontWeight("400"),
								text.UserSelect(options.UserSelectTypeNone),
							),
							text.New(
								"()",
								text.FontSize(14),
								text.FontColor("#4F8CBF"),
								text.FontWeight("400"),
								text.UserSelect(options.UserSelectTypeNone),
							),
							text.New(
								")",
								text.FontSize(14),
								text.FontColor("#AD77A8"),
								text.FontWeight("400"),
								text.UserSelect(options.UserSelectTypeNone),
							),
						},
					),
				},
				row.MainAxisAlignment(options.AxisAlignmentTypeStart),
				row.CrossAxisAlignment(options.AxisAlignmentTypeStart),
				row.Gap(6),
			),
			text.New(
				"}",
				text.FontSize(14),
				text.FontColor("#E0BD04"),
				text.FontWeight("400"),
				text.UserSelect(options.UserSelectTypeNone),
			),
		},
		column.MainAxisAlignment(options.AxisAlignmentTypeStart),
		column.CrossAxisAlignment(options.AxisAlignmentTypeStart),
		column.Gap(6),
	)

	return container.New(
		column.New(
			[]widget.BaseWidget{
				titleBar,
				packageName,
				spacer.New(spacer.Height(8)),
				imports,
				spacer.New(spacer.Height(8)),
				mainFunc,
			},
			column.MainAxisAlignment(options.AxisAlignmentTypeStart),
			column.Gap(6),
		),
		container.BackgroundColor("#282A36"),
		container.Height(breakpoint.All(240)),
		container.BorderRadius(8),
		container.Padding(breakpoint.All(16)),
		container.MaxWidth(540),
		container.WidthP(breakpoint.All(0.5), breakpoint.XS(1.0), breakpoint.SM(1.0), breakpoint.MD(0.75)),
	)
}

func cta() widget.BaseWidget {
	return grid.New(
		[]widget.BaseWidget{
			link.New(
				button.New(
					text.New(
						"Get Started",
						text.FontFamily("Ubuntu"),
						text.FontSize(14),
						text.FontColor("#FFFFFF"),
						text.FontWeight("500"),
						text.UserSelect(options.UserSelectTypeNone),
					),
					button.Width(breakpoint.All(100)),
				),
				link.Href("/docs#getting-started"),
			),
			link.New(
				button.New(
					row.New(
						[]widget.BaseWidget{
							icon.New(
								icondata.GitHub,
								icon.Fill("#FFFFFF"),
								icon.Height(breakpoint.All(16)),
								icon.Width(breakpoint.All(16)),
							),
							text.New(
								"GitHub",
								text.FontSize(14),
								text.FontColor("#FFFFFF"),
								text.FontWeight("500"),
								text.FontFamily("Ubuntu"),
								text.UserSelect(options.UserSelectTypeNone),
							),
						},
						row.MainAxisAlignment(options.AxisAlignmentTypeCenter),
						row.CrossAxisAlignment(options.AxisAlignmentTypeCenter),
						row.Gap(6),
					),
					button.BackgroundColor("#151B23"),
					button.Width(breakpoint.All(100)),
				),
				link.Href("https://github.com/gofred-io/gofred"),
				link.NewTab(true),
			),
		},
		grid.ColumnGap(8),
		grid.RowGap(8),
		grid.ColumnCount(
			breakpoint.All(2),
			breakpoint.XS(1),
		),
	)
}
